#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/*
Written by 6699 Tempest programmer Aaron Cook,
for 9399 Raven

The IR seeker is rather simple to use, for your usage it has only one function (it technically has 2, but the other one is almost useless)

The sensor has 10 possible values:
	0 - no reading
	1 - To your left and a bit behind, range is about 60 deg
	2 - Directly to left, 2 deg range
	3 - Position clockwise from 2, range of 60 deg
	etc.

The pattern is rather simple. It goes from 1 to 9, the odd numbers (1, 3, 5, 7, and 9) having a large viewing angle of about 60 deg
The even number are in between their respective odd numbers, and the range for them is essentially a line (it's really about 2 deg, but that's pretty accurate)

The range goes from behind directly to the left all the way to right after directly to the right. To get a better picture look at this picture: http://i.imgur.com/fVnqOjJ.png
*/

task main(){
while(true){
	//Use simple if's like this to specify what you want to do if the IR is a specific value
	if(SensorValue(IR) == 5){
		//Do stuff
	}

	if(SensorValue(IR) % 2 == 0){
		//If the value is even, very accurate
	}

	if(SensorValue(IR) % 2 == 1){
		//If the value is odd, not very accurate
	}
}
}
