#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  motorA,          Finger,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Left1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Elevator,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Right1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Right2,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Launch1,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     Launch2,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    IR1,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    IR2,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    Deploy,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/lego-ultrasound.h"

#define SeekerL 	msensor_S3_1
#define SeekerR 	msensor_S3_2
#define Gyro			msensor_S3_3
#define Ultra1		msensor_S3_4

#include "JoystickDriver.c"

int mSpeed = 30;
float tSpeed = 1440.0;
long totalDistance = 0;
float TPS;

task RPS(){
	int pos1;
	int pos2;

	while(true){
		totalDistance += nMotorEncoder(Right2);
		nMotorEncoder(Right2) = 0;
		pos1 = nMotorEncoder(Right2);
		wait1Msec(250);
		pos2 = nMotorEncoder(Right2);
		TPS = ((float)pos2 - (float)pos1)/(0.25);
	}
}

task main()
{
	StartTask(RPS);
	motor[Right2] = mSpeed;
	wait1Msec(500);
	ClearTimer(T2);
	totalDistance = 0;
	while(true){
		/*ClearTimer(T1);
		while(time1(T1) < 50){}
		mSpeed += 10*(tSpeed - TPS) + 0.01*(totalDistance - time1(T2)*TPS);
		motor[Right2] = mSpeed;*/
		eraseDisplay();
		nxtDisplayCenteredTextLine(2, "%f", TPS);
	}
}
