#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int motorSpeed = 35;
int motorSpeed2 = 35;

float minimum = 117.5;
float maximum = 124.9;
/*float CurrentRPM;

bool tooSlow;
bool tooFast;
bool justRight;

int fastCount = 0;
int slowCount = 0;
int rightCount = 0;

long slowTotal = 0;
long fastTotal = 0;
long rightTotal = 0;

float slowAvg;
float fastAvg;
float rightAvg;*/

float RPM(tMotor input){
	int position1;
	int position2;
	float rpm;

	wait1Msec(100);
	position1 = nMotorEncoder(input);
	wait1Msec(100);
	position2 = nMotorEncoder(input);

	rpm = abs(((float)position2 - (float)position1) * 600 / 1440);//converting from ticks/decisecond to rotations/second

	return rpm;
}

task main()
{
nMotorEncoder(Left) = 0;
eraseDisplay();


	motor[Left] = 0;
	motor[Right] = 0;
	wait1Msec(100);
	motor[Left] = motorSpeed;
	motor[Right] = motorSpeed2;
	wait1Msec(500);

	while(true){
		if(RPM(Left) < minimum){
			motorSpeed++;
			motor[Left] = motorSpeed;
		}

		if(RPM(Right) < minimum){
			motorSpeed2++;
			motor[Right] = motorSpeed2;
		}

		if(RPM(Left) > maximum){
			motorSpeed--;
			motor[Left] = motorSpeed;
		}

		if(RPM(Right) > maximum){
			motorSpeed2--;
			motor[Right] = motorSpeed2;
		}

		/*if((RPM(Left) >= minimum || RPM(Left) <= maximum) && (RPM(Right) >= minimum || RPM(Right) <= maximum)){
			ClearTimer(T1);
			while((RPM(Left) >= minimum || RPM(Left) <= maximum) && (RPM(Right) >= minimum || RPM(Right) <= maximum)){
				CurrentRPM = RPM(Left);
				justRight = true;
				nxtDisplayCenteredTextLine(3, "RPM:%f", RPM(Left));
			}
			justRight = false;
			rightTotal += time1(T1);
			rightCount++;
		}

		slowAvg = slowTotal/slowCount;
		fastAvg = fastTotal/fastCount;
		rightAvg = rightTotal/rightCount;*/
	}
}
