#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int motorSpeed = 75;

float target = 124.2;
float minimum = 120.3;
float maximum = 130.5;

bool tooSlow;
bool tooFast;
bool justRight;
int slowFor = 0;
int fastFor = 0;
int rightFor = 0;

float RPM(tMotor input){
	int position1;
	int position2;
	float rpm;

	position1 = nMotorEncoder(input);
	wait1Msec(100);
	position2 = nMotorEncoder(input);

	rpm = ((float)position2 - (float)position1) * 600 / 1440;//converting from ticks/decisecond to rotations/second

	return rpm;
}

task main()
{
nMotorEncoder(Left) = 0;
eraseDisplay();


	motor[Left] = 0;
	wait1Msec(100);
	motor[Left] = motorSpeed;
	wait1Msec(500);

	while(true){
		if(RPM(Left) < minimum){
			eraseDisplay();
			ClearTimer(T1);
			while(RPM(Left) < minimum){
				tooSlow = true;
				motorSpeed++;
				motor[Left] = motorSpeed;
				wait1Msec(50);//Get to speed;
			}
			tooSlow = false;
			slowFor += time1(T1);
		}

		if(RPM(Left) > maximum){
			eraseDisplay();
			ClearTimer(T1);
			while(RPM(Left) < maximum){
				tooFast = true;
				motorSpeed--;
				motor[Left] = motorSpeed;
				wait1Msec(50);
			}
			tooFast = false;
			fastFor += time1(T1);
		}

		if(RPM(Left) >= minimum || RPM(Left) <= maximum){
			eraseDisplay();
			nxtDisplayCenteredTextLine(0, "You're good");
			nxtDisplayCenteredTextLine(1, "to launch!");
			ClearTimer(T1);
			while(RPM(Left) >= minimum || RPM(Left) <= maximum){
				justRight = true;
				nxtDisplayCenteredTextLine(3, "RPM:%f", RPM(Left));
			}
			justRight = false;
			rightFor += time1(T1);
		}
	}
}
