#pragma config(Sensor, S1,     IRSeeker,       sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

bool visible;
int value;

task main()
{
eraseDisplay();
while(true){
		if(SensorValue(IRSeeker) != 0){
			visible = true;
		}else{
			visible = false;
			PlaySound(soundBeepBeep);
			wait1Msec(1000);
		}
		nxtDisplayCenteredTextLine(1, "%i", SensorValue(IRSeeker));
		value = SensorValue(IRSeeker);

}
}
