#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S2_C1_1,    IR1,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    IR2,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
while(true){
	if(joy1Btn(2) && !joy1Btn(4)){
		servo[IR1] = 30;
		servo[IR2] = 210;
	}
	if(joy1Btn(4) && !joy1Btn(2)){
		servo[IR1] = 255;
		servo[IR2] = 0;
	}
}
}
