#pragma config(Sensor, S1,     IRSeeker,       sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

bool visible;
int value;

task main()
{
eraseDisplay();
while(true){
		nxtDisplayCenteredTextLine(1, "%i", SensorValue(IRSeeker));

}
}
