#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     Touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
//This is the same thing just without using encoders

//normal code
ClearTimer(T1);
motor[Right] = 75;

while(!SensorValue(Touch)){//Theoretically we should be waiting for a sensor of some sort
	//in an autonomous...
	if(time1(T1) > 1000){
		motor[Right] = 0;//stop
		break;//break the while loop
	}
}



}
