#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int motorDelay = 200;//Datalog this!


//This is a float that gives you the RPM of a certain motor
float RPM(tMotor input){
	int position1;
	int position2;
	float rpm;

	position1 = nMotorEncoder(input);
	wait1Msec(100);
	position2 = nMotorEncoder(input);

	rpm = (position2 - position1) * 600 / 1440;//converting from ticks/decisecond to rotations/minute

	return rpm;
}




task main()
{
//This is the code before hand
nMotorEncoder(Right) = 0;
motor[Right] = 75;
while(nMotorEncoder(Right) < 1440){//rotate one rotation
	//wait
}
motor[Right] = 0;





//Checking encoder with the encoder itself
nMotorEncoder(Right) = 0;
ClearTimer(T1);//We are checking over intervals of time

motor[Right] = 75;
wait1Msec(motorDelay);//Get motor up to speed

while(nMotorEncoder(Right) < 1440){//rotate one rotation
	if(time1(T1) > 500){
		if(RPM(Right) < 40) break;//This speed is slower than normal
		ClearTimer(T1);
	}
}
motor[Right] = 0;





//Checking encoder with a timer
nMotorEncoder(Right) = 0;
ClearTimer(T1);//Were using a timer

motor[Right] = 75;

while(nMotorEncoder(Right) < 1440){//rotate one rotation
	if(time1(T1) > 3000){//If the turn shouldn't take any longer than 3000 milliseconds
		break;
		//break the while loop
	}
}
motor[Right] = 0;
}
