#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     Ultra2,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     Right1,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Left1,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Launch1,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     Launch2,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    Deploy,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/lego-ultrasound.h"

#define SeekerL 	msensor_S3_1
#define SeekerR 	msensor_S3_2
#define Gyro			msensor_S3_3
#define Ultra1		msensor_S3_3

int modPos;
int mSpeed = 50;
int lSpeed = 30;
float minimumRPM = 120.3;
float maximumRPM = 130.5;
float tooSlow = 0.2;

float RPM(tMotor input){
	int position1;
	int position2;
	float rpm;

	wait1Msec(100);
	position1 = nMotorEncoder(input);
	wait1Msec(100);
	position2 = nMotorEncoder(input);

	rpm = abs(((float)position2 - (float)position1) * 600 / 1440);//converting from ticks/decisecond to rotations/second

	return rpm;
}



void Right(int speed){
	motor[Right1] = speed;
	motor[Right2] = speed;
}

void Left(int speed){
	motor[Left1] = speed;
	motor[Left2] = speed;
}



void goStraight(const int speed, const int angle){
	if(HTGYROreadCal(Gyro) < angle-5){
			Right(speed + 1);
			Left(speed - 1);
		}
		else if(HTGYROreadCal(Gyro) > angle+5){
			Right(speed - 1);
			Left(speed + 1);
		}
		else{
			Right(speed);
			Left(speed);
		}

		//Obstacle
		if(RPM(Right1) < tooSlow && time1(T2) > 2000){
			Right(0);
			Left(0);
			wait1Msec(2000);
			Right(speed);
			Left(speed);
			ClearTimer(T2);
		}
		if(RPM(Left1) < tooSlow && time1(T2) > 2000){
			Right(0);
			Left(0);
			wait1Msec(2000);
			Right(speed);
			Left(speed);
			ClearTimer(T2);
		}
}



void checkObstacle(bool forward){
	if(forward){
		if(USreadDist(Ultra1) <= 50 && USreadDist(Ultra1) >= 20){
			Right(USreadDist(Ultra1) - 20);
			Left(USreadDist(Ultra1) - 20);
		}
		else if(USreadDist(Ultra1) < 20){
			Right(0);
			Left(0);
		}
		else{
			Right(mSpeed);
			Left(mSpeed);
		}
	}

	else{
		if(SensorValue(Ultra2) <= 50 && SensorValue(Ultra2) >= 20){
			Right(-(SensorValue(Ultra2) - 20));
			Left(-(SensorValue(Ultra2) - 20));
		}
		else if(SensorValue(Ultra2) < 20){
			Right(0);
			Left(0);
		}
		else{
			Right(-mSpeed);
			Left(-mSpeed);
		}
	}
}



void triangulate(){
bool Triangulating = true;

while(Triangulating){
	if(HTIRS2readDCDir(SeekerL) < 6){
		if(HTIRS2readDCDir(SeekerR) < 4){
			//left
			Right(mSpeed / 2);
			Left(-mSpeed / 2);
		}

		if(HTIRS2readDCDir(SeekerR) > 4){
			//forward
			Right(mSpeed / 2);
			Left(mSpeed / 2);
		}

		if(HTIRS2readDCDir(SeekerR) == 4){
			//left
			Right(mSpeed / 2);
			Left(-mSpeed / 2);
		}
	}

	if(HTIRS2readDCDir(SeekerL) > 6){
		if(HTIRS2readDCDir(SeekerR) < 4){
			//back
			Right(-mSpeed / 2);
			Left(-mSpeed / 2);
		}

		if(HTIRS2readDCDir(SeekerR) > 4){
			//right
			Right(-mSpeed / 2);
			Left(mSpeed / 2);
		}

		if(HTIRS2readDCDir(SeekerR) == 4){
			//right
			Right(-mSpeed / 2);
			Left(mSpeed / 2);
		}
	}

	if(HTIRS2readDCDir(SeekerL) == 6){
		if(HTIRS2readDCDir(SeekerR) < 4){
			//left
			Right(-mSpeed / 2);
			Left(mSpeed / 2);
		}

		if(HTIRS2readDCDir(SeekerR) > 4){
			//right
			Right(-mSpeed / 2);
			Left(mSpeed / 2);
		}

		if(HTIRS2readDCDir(SeekerR) == 4){
			//stop, break
			Right(0);
			Left(0);
			Triangulating = false;
		}
	}
}
}



void launch(){
	bool Launched = false;

	while(!Launched)
		if(HTIRS2readDCDir(SeekerR) == 4 && HTIRS2readDCDir(SeekerL) == 6){
			motor[Launch1] = lSpeed;
			motor[Launch2] = lSpeed;
			wait1Msec(2000);
			ClearTimer(T2);
			do{
				if((RPM(Launch1) + RPM(Launch2))/2 < minimumRPM){
					lSpeed += 2;//The ball will add resistance, so incriment by 2
					motor[Launch1] = lSpeed;
					motor[Launch2] = lSpeed;
				}
				else if((RPM(Launch1) + RPM(Launch2))/2 > maximumRPM){
					lSpeed--;
					motor[Launch1] = lSpeed;
					motor[Launch2] = lSpeed;
				}
				else{
					//Deploy
					servo[Deploy] = 90;
					if(time1(T2) > 5000){
						Launched = true;
						servo[Deploy] = 180;
					}
				}
			}while(!Launched);
		}
		else{
			triangulate();
		}
}



void straight(bool dir, int distance, int angle){
	int factor;

	if(dir){
		factor = 1;
	}else{
		factor = -1;
	}

	nMotorEncoder(Right1) = 0;
	nMotorEncoder(Left1) = 0;

	Right(factor*mSpeed);
	Left(factor*mSpeed);

	while(abs(nMotorEncoder(Right1)) < distance && abs(nMotorEncoder(Left1)) < distance){
		goStraight(factor*mSpeed, angle);
	}

	Right(0);
	Left(0);
}



void left(int angle, int distance){
	nMotorEncoder(Right1) = 0;
	nMotorEncoder(Left1) = 0;

	Right(mSpeed / 2);
	Left(-mSpeed / 2);

	while(abs(nMotorEncoder(Right1)) < distance && abs(nMotorEncoder(Left1)) < distance && HTGYROreadCal(Gyro) < angle){
	}

	Right(0);
	Left(0);
}



void right(int angle, int distance){
	nMotorEncoder(Right1) = 0;
	nMotorEncoder(Left1) = 0;

	Right(-mSpeed / 2);
	Left(mSpeed / 2);

	while(abs(nMotorEncoder(Right1)) < distance && abs(nMotorEncoder(Left1)) < distance && HTGYROreadCal(Gyro) > angle){
	}

	Right(0);
	Left(0);
}



void findPos(){
	if(HTIRS2readDCDir(SeekerR) == 5 && HTIRS2readDCDir(SeekerL) == 5) modPos = 1;

	if(HTIRS2readDCDir(SeekerR) == -1 && HTIRS2readDCDir(SeekerL) == -1) modPos = 2;

	if(HTIRS2readDCDir(SeekerR) == 3 && HTIRS2readDCDir(SeekerL) == 3) modPos = 3;
}



task main(){
	straight(true, 1440*5, 0)	;
	findPos();

	if(modPos == 1){
		left(90, 1440);
		straight(true, 1440*5, 90);
		right(0, 1440);
		straight(true, 1440/2, 0);
		right(-90, 1440);
		launch();
	}
	else if(modPos == 2){
		straight(true, 1440/2, 0);
		left(135, (1440*3) / 2);
		straight(true, 1440*5, 135);
		right(45, 1440);
		straight(true, 1440/2, 45);
		right(-45, 1440);
		launch();
	}
	else if(modPos == 3){
		straight(true, 1440, 0);
		straight(false, 1440*3, 0);
		left(90, 1440);
		straight(true, 1440/2, 45);
		right(0, 1440);
		launch();
	}
}
