#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     Right1,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Left1,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Launch1,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     Launch2,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-gyro.h"

#define SeekerL 	msensor_S3_1
#define SeekerR 	msensor_S3_2
#define Gyro			msensor_S3_3

float trans = 0;
int mSpeed = 50;
float tooSlow = 0.2;

float RPM(tMotor input){
	int position1;
	int position2;
	float rpm;

	wait1Msec(100);
	position1 = nMotorEncoder(input);
	wait1Msec(100);
	position2 = nMotorEncoder(input);

	rpm = abs(((float)position2 - (float)position1) * 600 / 1440);//converting from ticks/decisecond to rotations/second

	return rpm;
}



void Right(int speed){
	motor[Right1] = speed;
	motor[Right2] = speed;
}

void Left(int speed){
	motor[Left1] = speed;
	motor[Left2] = speed;
}



void forward(int distance){
	nMotorEncoder(Right1) = 0;
	nMotorEncoder(Left1) = 0;

	Right(mSpeed);
	Left(mSpeed);

	ClearTimer(T2);

	while(nMotorEncoder(Right1) < distance && nMotorEncoder(Left1) < distance){
		//Keep straight
		if(HTGYROreadCal(Gyro) < -5){
			Right(mSpeed + 1);
			Left(mSpeed - 1);
		}
		else if(HTGYROreadCal(Gyro) > 5){
			Right(mSpeed - 1);
			Left(mSpeed + 1);
		}
		else{
			Right(mSpeed);
			Left(mSpeed);
		}

		//Obstacle
		if(RPM(Right1) < tooSlow && time1(T2) > 2000){
			Right(0);
			Left(0);
			wait1Msec(2000);
			Right(mSpeed);
			Left(mSpeed);
			ClearTimer(T2);
		}
		if(RPM(Left1) < tooSlow && time1(T2) > 2000){
			Right(0);
			Left(0);
			wait1Msec(2000);
			Right(mSpeed);
			Left(mSpeed);
			ClearTimer(T2);
		}
	}

	Right(0);
	Left(0);

	trans = 1;
}



void findPos(){
	if(HTIRS2_DC_DIR(SeekerR) == 5 && HTIRS2_DC_DIR(SeekerL) == 5) trans = 2.1;

	if(HTIRS2_DC_DIR(SeekerR) == -1 && HTIRS2_DC_DIR(SeekerL) == -1) trans = 2.2;

	if(HTIRS2_DC_DIR(SeekerR) == 3 && HTIRS2_DC_DIR(SeekerL) == 3) trans = 2.3;
}

task main()
{
waitForStart();
HTGYROstartCal(Gyro);
if(trans == 0) forward(3000);
if(trans == 1) findPos();
}
