#pragma config(Sensor, S1,     HTSMUX,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/lego-ultrasound.h"

#define SeekerL 	msensor_S3_1
#define SeekerR 	msensor_S3_2
#define Gyro			msensor_S3_3
#define Ultra1		msensor_S3_4

task main(){
	eraseDisplay();
	HTGYROstartCal(Gyro);
	while(true){
		nxtDisplayCenteredTextLine(1, "%i", HTIRS2readDCDir(SeekerL));
		nxtDisplayCenteredTextLine(2, "%i", HTIRS2readDCDir(SeekerR));
		nxtDisplayCenteredTextLine(3, "%i", HTGYROreadCal(Gyro));
		nxtDisplayCenteredTextLine(4, "%i", USreadDist(Ultra1));
	}
}
